config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'edit_profile_pic' => 'users#edit_profile_pic', as: :edit_profile_pic
  patch 'crop_profile_pic' => 'users#crop_profile_pic', as: :crop_profile_pic
  delete 'remove_profile_pic' => 'users#remove_profile_pic', as: :remove_profile_pic

  put 'update_with_password' => 'users#update_with_password', as: :update_with_password
  put 'update_without_password' => 'users#update_without_password', as: :update_without_password

  root 'welcome#index'

  resources :todo_lists do
    member do
      get 'new_user'
      post 'share'
      delete 'destroy_share/:user_id' => 'todo_lists#destroy_share', as: :destroy_share
      get 'new_todo_item'
      post 'add_todo_item'
      delete 'delete_todo_item/:todo_item_id' => 'todo_lists#delete_todo_item', as: :delete_todo_item
      get 'update_todo_item/:todo_item_id' => 'todo_lists#update_todo_item', as: :update_todo_item
      get 'update_state'
      put 'sort'
    end
  end

  resources :tasks do
    put :sort, on: :collection
  end

end

app/views/snippets/_app_header.html.erb
<div id="header">
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <%= link_to(image_tag("logo.png"), root_path, class: "navbar-brand") %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="glyphicon glyphicon-resize-vertical"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-right non-usernav">
        <%- if controller_name != 'sessions' %>
            <li>
              <%= link_to new_session_path(resource_name) do %>
                  <span class="glyphicon glyphicon-log-in"></span>
                  <span class="txt"> Sign in</span>
              <% end %>
            </li>
        <% end -%>

        <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
            <li>
              <%= link_to new_registration_path(resource_name) do %>
                  <span class="glyphicon glyphicon-th"></span>
                  <span class="txt"> Sign Up</span>
              <% end %>
            </li>
        <% end -%>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </nav>
  <!--/navbar -->
</div>

app/views/snippets/_flash_messages.html.erb
<div id="flash_msg">
  <script>
      var notice_key = '<%= flash.first[0] rescue ''%>';
      var notice_msg = '<%= flash.first[1] rescue ''%>';
      $(function () {
          if (notice_msg != '' && notice_key != '') {
              display_notice(notice_key, notice_msg)
              notice_key = notice_msg = ''
          }
      })
  </script>
</div>

app/views/snippets/_header.html.erb
<div id="header">
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <%= link_to(image_tag("logo.png"), root_path, class: "navbar-brand") %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="glyphicon glyphicon-arrow-4"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-right usernav">
        <li>
          <%= link_to root_url, class: 'menu-option' do %>
              <span class="glyphicon glyphicon-home"></span>
              <span class="txt">  Home</span>
          <% end %>
        </li>
        <li class="dropdown menu-option">
          <a href="javascript:void(0);" class="dropdown-toggle avatar menu-option" data-toggle="dropdown">
            <%= image_tag current_user.stamp_image, class: "image user_profile_pic" %>
            <span class="txt"><%= current_user.email %></span>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li class="menu">
              <ul>
                <li>
                  <%= link_to edit_user_registration_path do %>
                      <span class="glyphicon glyphicon-user"></span>
                      View Profile
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                      <span class="glyphicon glyphicon-log-out"></span>
                      Sign Out
                  <% end %>
                </li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </div>

    <!--/.nav-collapse -->
  </nav>
  <!--/navbar -->

</div>
<!--End #header -->