config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'edit_profile_pic' => 'users#edit_profile_pic', as: :edit_profile_pic
  patch 'crop_profile_pic' => 'users#crop_profile_pic', as: :crop_profile_pic
  delete 'remove_profile_pic' => 'users#remove_profile_pic', as: :remove_profile_pic

  put 'update_with_password' => 'users#update_with_password', as: :update_with_password
  put 'update_without_password' => 'users#update_without_password', as: :update_without_password

  root 'welcome#index'

  resources :todo_lists do
    member do
      get 'new_user'
      post 'share'
      delete 'destroy_share/:user_id' => 'todo_lists#destroy_share', as: :destroy_share
      get 'new_todo_item'
      post 'add_todo_item'
      delete 'delete_todo_item/:todo_item_id' => 'todo_lists#delete_todo_item', as: :delete_todo_item
      get 'update_todo_item/:todo_item_id' => 'todo_lists#update_todo_item', as: :update_todo_item
      get 'update_state'
      put 'sort'
    end
  end

  resources :tasks do
    put :sort, on: :collection
  end

end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  # ==== Validations ==============================================
  validates :description, presence: true, length: 2..170

  # ==== Associations =============================================
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  has_and_belongs_to_many :users, -> { distinct }
  has_many :todo_items, dependent: :destroy

  # ==== Call back ================================================
  before_destroy :destroy_allowed?

  # ==== State machine =============================================
  state_machine :state, :initial => :open do
    event :assign do
      transition all => :open
    end

    event :complete do
      transition any => :done
    end

    before_transition :done => any, do: :stop_state_update
    after_transition :on => :complete, do: :done_all_items
  end

  def stop_state_update
    return false
  end

  def done_all_items
    todo_items.each do |item|
      item.update(state: 'done')
    end
  end

  def add_user(email)
    _user = User.where(email: email).first
    return false unless _user
    return true if users << _user
  end

  def delete_user(user)
    return true if users.delete(user)
    false
  end

  def destroy_allowed?
    state != 'done'
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_todo_list, except: [:new, :create]
  before_action :fetch_todo_item, only: [:delete_todo_item, :update_todo_item]

  def new
    @todo_list = TodoList.new
  end

  def create
    @todo_list = current_user.owned_todo_lists.new(todo_list_params)
    if @todo_list.save
      redirect_to @todo_list, notice: 'ToDo list was successfully created.'
    else
      render :edit
    end
  end

  def index
    @todos = params[:state] ? current_user.all_todo_lists(params[:state]) : current_user.all_todo_lists
  end

  def edit
  end

  def show
  end

  def update
    if @todo_list.update(todo_list_params)
      redirect_to @todo_list, notice: 'ToDo list updated.'
    else
      render :edit
    end
  end

  def destroy
    _notice = @todo_list.destroy ? 'ToDo list was successfully destroyed.' : 'Unable to destroy ToDo list'
    redirect_to todo_lists_url, notice: _notice
  end

  def new_user
  end

  def share
    unless @todo_list.add_user(user_params[:email])
      redirect_to @todo_list, notice: 'Unable to share ToDo list' and return
    end
  end

  def sort
    params[:order].each do |key,value|
      _item = @todo_list.todo_items.where(id: value[:id]).first
      _item.update_attribute(:position, value[:position])
    end
    render body: nil
  end

  def destroy_share
    _notice = @todo_list.delete_user(User.where(id: params[:user_id]).first) ? 'User removed successfully.' : 'Unable to remove user.'
    redirect_to @todo_list, notice: _notice
  end

  def new_todo_item
    @todo_item = @todo_list.todo_items.build
  end

  def add_todo_item
    redirect_to @todo_list, notice: @todo_list.todo_items.create(todo_item_params) ? 'List item added.' : 'Unable to add item.'
  end

  def delete_todo_item
    redirect_to @todo_list and return unless @todo_item
  end

  def update_todo_item
    updated = @todo_item.send(params[:event]) if params[:event]
    flash[:notice] = updated ? 'ToDo item updated' : 'Unable to update'
  end

  def update_state
    updated = @todo_list.send(params[:event]) if params[:event]
    flash[:notice] = updated ? 'ToDo list updated' : 'Unable to update'
  end

  private

  def fetch_todo_list
    @todo_list = TodoList.where(id: params[:id]).first
  end

  def fetch_todo_item
    @todo_item = @todo_list.todo_items.where(id: params[:todo_item_id]).first
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def todo_list_params
    params.require(:todo_list).permit(:name, :description)
  end

  def todo_item_params
    params.require(:todo_item).permit(:description)
  end

  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title" id="myModalLabel">ToDo List</h4>
</div>
<div class="modal-body">
  <%= form_for(todo_list, remote: true) do |f| %>

      <div class="field form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', autofocus: true %>
      </div>
      <div class="field form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit class: "btn btn-default btn-primary pull-right", data: {disable_with: 'Saving...'} %>
        <div class="clearfix"></div>
      </div>
  <% end %>
</div>

app/views/todo_lists/_items_tab.html.erb
<div role="tabpanel" class="tab-pane active" id="todo_items">
  <div class="col-md-12" style="display: <%= todo_list.todo_items.count.zero? ? 'visible' : 'none' %>">
    <div class="text-right form-group text-center">
      <%= link_to 'Add ToDo Item', new_todo_item_todo_list_path(todo_list),
                  class: 'btn btn-primary btn-lg', remote: true %>
    </div>
    <div class="no_items">
      <div class="text-center">
        <div class="clearfix"></div>
        <span class="glyphicon glyphicon-list"></span>

        <p>No items in list. Please add some. </p>
      </div>
    </div>
  </div>

  <%= render partial: 'todo_lists/todo_items_list', locals: {todo_list: todo_list} %>
</div>

<script>
    function updateItem(element, id) {
        var todo_item_path = '<%= update_todo_item_todo_list_path(todo_list, '__todo_item_id__')%>'.replace("__todo_item_id__", id);
        _data = {};
        if ($(element).is(":checked")) {
            _data['event'] = 'complete'
        } else {
            _data['event'] = 'assign'
        }
        updateList();
        $.ajax({
            type: 'GET',
            url: todo_item_path,
            data: _data,
            dataType: 'script'
        })
    }

    function updateList() {
        if ($('.chk_item:checked').length == $('.chk_item').length) {
            $('#check_list_<%= todo_list.id %>').prop('checked', true);
        }
    }

    function mark_list_update(element) {
        var todo_item_path = '<%= update_state_todo_list_path(todo_list)%>';
        _data = {};
        if ($(element).is(":checked")) {
            _data['event'] = 'complete'
        } else {
            _data['event'] = 'assign'
        }
        $.ajax({
            type: 'GET',
            url: todo_item_path,
            data: _data,
            dataType: 'script'
        })
    }
</script>

app/views/todo_lists/_shared_user.html.erb
<div class="users-listing">
  <div class="col-sm-4 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h4><%= user.full_name %></h4>

        <p><%= user.email %></p>
      </div>
      <div class="box">
        <% if todo_list.owner == current_user %>
            <%= link_to destroy_share_todo_list_path(todo_list, user), method: :delete, class: 'pull-right', data: {confirm: 'Are you sure?'}, remote: true do %>
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/todo_lists/_todo_items_list.html.erb
<ul class="list-group sortable" id="list_group_<%= todo_list.id %>" data-id="<%= todo_list.id %>">
  <% unless todo_list.todo_items.count.zero? %>
      <p class="list_status status_<%= todo_list.state %>" id="list_status_<%= todo_list.id %>">
        <input type="checkbox" id="check_list_<%= todo_list.id %>" <%= todo_list.state == 'done' ? 'checked=true' : '' %> onchange="mark_list_update(this);">
        Done </p>
  <% end %>
  <% todo_list.todo_items.each do |item| %>
      <li class="list-group-item to_do_items item_<%= item.state %>" id="item_<%= item.id %>" data-id="<%= item.id %>">
        <input type="checkbox" id="check_item_<%= item.id %>" class="chk_item" <%= item.state == 'done' ? 'checked=true' : '' %>" onchange="updateItem(this,'<%= item.id %>');">

        <p><%= item.description %></p>
        <%= link_to delete_todo_item_todo_list_path(todo_list, item), method: :delete, class: 'pull-right', data: {confirm: "Are you sure, you can't undo this action?"}, remote: true do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        <% end %>
      </li>
  <% end %>
</ul>

<script>
  $(document).ready(function(){
    var _elements = $('.list-group-item.to_do_items');
    set_positions(_elements);
    sort_list(_elements);
  });
</script>

app/views/todo_lists/_todo_list_view.html.erb
<div class='move-bottom'>
  <div class="col-lg-12">
    <h2 class="page-header"><%= @todo_list.name %>
    <p class="owner_info">
      <b>Owner: </b> <%= @todo_list.owner.full_name %>
    </p>
    </h2>
  </div>

  <div class="row">
    <div class="col-xs-6">
      <p class="description-short"><%= @todo_list.description %></p>
    </div>
    <div class="col-xs-6 marginB10 text-right">
      <%= link_to edit_todo_list_path(@todo_list), class: 'btn btn-default', remote: true do %>
          <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
          Edit
      <% end %>
      <%= link_to new_todo_item_todo_list_path(@todo_list), class: 'btn btn-primary', remote: true do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          Add New ToDo Item
      <% end %>
    </div>

  </div>

  <div class="col-lg-12">
    <div id="newtabs">
      <%= render partial: 'todo_lists/list_tabs', locals: {todo_list: @todo_list} %>
    </div>
  </div>

</div>

app/views/todo_lists/_users_tab.html.erb
<div role="tabpanel" class="tab-pane" id="shared_users">
  <% if todo_list.owner == current_user %>
      <div class="<%= todo_list.users.count.zero? ? 'text-right form-group text-center' : 'text-right form-group' %>">
        <%= link_to 'Share', new_user_todo_list_path(todo_list),
                    class: 'btn btn-primary btn-lg', remote: true %>

      </div>
  <% end %>

  <div class="col-md-12" style="display: <%= todo_list.users.count.zero? ? 'visible' : 'none' %>">
    <div class="no_users">
      <div class="text-center">
        <div class="clearfix"></div>
        <span class="glyphicon glyphicon-hand-up"></span>
        <p>No collaborators yet. Please add some collaborators in your project. </p>
      </div>
    </div>
  </div>

  <div class="row" id="shared_users">
    <%= render partial: 'todo_lists/shared_user', collection: todo_list.users, as: :user, locals: {todo_list: todo_list} %>
  </div>
</div>

app/views/todo_lists/delete_todo_item.js.erb
<% if @todo_item.destroy %>
$('#item_<%= @todo_item.id %>').remove();
display_notice('notice', 'ToDo item deleted.');
<% else %>
display_notice('notice', 'Unable to delete ToDo item.');
<% end %>

<% if @todo_list.todo_items.count.zero? %>
$('#todo_items').replaceWith("<%=j render partial: 'todo_lists/items_tab', locals: {todo_list: @todo_list} %>");
$('#todo_list_<%= @todo_list.id %>').html('<li class="list-group-item disabled"> No items in list.</li>')
<% end %>

app/views/todo_lists/edit.js.erb
$('div.modal-content').html("<%=j render partial: 'todo_lists/form', locals: {todo_list: @todo_list} %>");
$('#modal-window').modal('show');

app/views/todo_lists/index.js.erb
$('#todo_lists').replaceWith("<%=j render partial: 'welcome/list_of_todos', locals: {todos: @todos} %>");
$('.minimize').off('click').on('click', function () {
    $(this).parents('.panel').children('.panel-body').slideToggle("slow");
});

app/views/todo_lists/new.js.erb
$('div.modal-content').html("<%=j render partial: 'todo_lists/form', locals: {todo_list: @todo_list} %>")
$('#modal-window').modal('show');
$('#modal-window').on('shown.bs.modal', function () {
    $('#todo_list_name').focus();
});

app/views/todo_lists/new_todo_item.js.erb
$('div.modal-content').html("<%=j render partial: 'todo_lists/todo_item_form', locals: {todo_item: @todo_item} %>");
$('#modal-window').modal('show');
$('#modal-window').on('shown.bs.modal', function () {
    $('#todo_item_description').focus();
});

app/views/todo_lists/share.js.erb
$('#shared_users').html("<%=j render partial: 'todo_lists/shared_user', collection: @todo_list.users, as: :user, locals: {todo_list: @todo_list} %>")

app/views/todo_lists/show.js.erb
$('#modal-window').modal('hide');
$('#main_content').html("<%=j render partial: 'todo_lists/todo_list_view', locals: {todo_list: @todo_list} %>");

app/views/todo_lists/update_state.js.erb
$('#list_group_<%= @todo_list.id %>').replaceWith('<%=j render partial: 'todo_lists/todo_items_list', locals: {todo_list: @todo_list} %>');
$('#check_list_<%= @todo_list.id %>').prop('checked', <%= @todo_list.state == 'done' %>);
$('p#list_status_<%= @todo_list.id %>').removeClass('<%= @todo_list.state_paths.to_states.collect{|x| "status_#{x.to_s}"}.join(" ") %>').addClass('status_<%= @todo_list.state %>');