config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'edit_profile_pic' => 'users#edit_profile_pic', as: :edit_profile_pic
  patch 'crop_profile_pic' => 'users#crop_profile_pic', as: :crop_profile_pic
  delete 'remove_profile_pic' => 'users#remove_profile_pic', as: :remove_profile_pic

  put 'update_with_password' => 'users#update_with_password', as: :update_with_password
  put 'update_without_password' => 'users#update_without_password', as: :update_without_password

  root 'welcome#index'

  resources :todo_lists do
    member do
      get 'new_user'
      post 'share'
      delete 'destroy_share/:user_id' => 'todo_lists#destroy_share', as: :destroy_share
      get 'new_todo_item'
      post 'add_todo_item'
      delete 'delete_todo_item/:todo_item_id' => 'todo_lists#delete_todo_item', as: :delete_todo_item
      get 'update_todo_item/:todo_item_id' => 'todo_lists#update_todo_item', as: :update_todo_item
      get 'update_state'
      put 'sort'
    end
  end

  resources :tasks do
    put :sort, on: :collection
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @todos = current_user.all_todo_lists
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_list_of_todos.html.erb
<div class="todo_list_container" id="todo_lists">
  <div class="col-md-12" style="display: <%= todos.count.zero? ? 'visible' : 'none' %>">
    <div class="no_items">
      <div class="text-center">
        <div class="clearfix"></div>
        <span class="glyphicon glyphicon-tasks"></span>

        <p>No ToDo list available. </p>
      </div>
    </div>
  </div>

  <% todos.each do |to_do| %>
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4>
              <%= link_to to_do.name, todo_list_path(to_do), remote: true %>
            </h4>
            <a class="minimize" href="javascript:void(0);"></a>
          </div>
          <div class="panel-body">
            <p><%= to_do.description %><span class="right status_<%= to_do.state %>"><%= to_do.state %></span></p>
            <p><b>owner: </b> <%= to_do.owner.full_name %></p>
            <ul class="list-group sortable" data-id="<%= to_do.id %>" id="todo_list_<%= to_do.id %>">
              <% if to_do.todo_items.count.zero? %>
                  <li class="list-group-item disabled"> No items in list.</li>
              <% else %>
                  <!--<h5>ToDo Items:</h5>-->
                  <% to_do.todo_items.each do |item| %>
                      <li class="list-group-item item_<%= item.state %>" data-id="<%= item.id %>" id="item_<%= item.id %>">
                        <%= item.description %>
                        <%= link_to delete_todo_item_todo_list_path(to_do, item), method: :delete, class: 'pull-right', data: {confirm: "Are you sure, you can't undo this action?"}, remote: true do %>
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        <% end %>
                      </li>
                  <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
  <% end %>
</div>


<script>
  $(document).ready(function(){
    var _elements = $('.list-group.sortable .list-group-item');
    set_positions(_elements);
    sort_list(_elements);
  });
</script>

app/views/welcome/index.html.erb
<div class='move-bottom'>
  <div class="col-lg-12">
    <h2 class="page-header">Dashboard</h2>
  </div>
  <% if @todos.count.zero? %>
      <div class="text-center no_project" id="no_project">
        <div class="col-md-12">
          <%= link_to new_todo_list_path, remote: true do %>
              <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
              <i class="fa fa-file-pdf-o"></i>
              <h4><b>Seems you are new.<br/>Click here to get started.</b></h4>
          <% end %>
        </div>
        <br class="clearfix">
      </div>
  <% else %>
      <div class="row">
        <div class="col-xs-12 marginB10 text-right">
          <%= link_to new_todo_list_path, remote: true, class: 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
              Add New ToDo List
          <% end %>
          <span class="right todo_select">
          <%= select('todo_list', 'status', TodoList.pluck(:state).uniq.map { |state| [state] }.unshift(['All ToDos', nil]), {}, {class: 'form-control', id: 'select-state'}) %>
          </span>
        </div>
      </div>
      <%= render partial: 'welcome/list_of_todos', locals: {todos: @todos} %>
  <% end %>
</div>

<script>
    $('.minimize').off('click').on('click', function () {
        $(this).parents('.panel').children('.panel-body').slideToggle("slow");
    });

    $('#select-state').on('change', function () {
        _state = $(this).val();
        var data_json = {state: _state};
        $.ajax({
            type: 'GET',
            url: '<%= todo_lists_path %>',
            data: data_json,
            dataType: 'script'
        })
    })
</script>